a  = input('Digite qualquer valor ')
print("O tipo primitivo do valor {} é:".format(a),type(a))
print('O valor {} só tem espaços?'.format(a), a.isspace())
print('O valor {} é numérico?'.format(a), a.isnumeric())
print('O valor {} é numérico?'.format(a), a.isalpha())
print('O valor {} é numérico?'.format(a), a.isalnum())
print('O valor {} é numérico?'.format(a), a.isupper())
print('O valor {} é numérico?'.format(a), a.islower())
print('O valor {} é numérico?'.format(a), a.istitle())